spring:
  application:
    name: battle-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
      uri: ${CONFIG_SERVER_URI:http://config-server:8888}
      fail-fast: false
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:battle-service}
    prefer-ip-address: false