spring:
  application:
    name: battle-service
  config:
    import: "optional:configserver:"
  cloud:
    config:

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:battle-service}
    prefer-ip-address: false

---
spring:
  profiles:
    active: local

server:
  port: 8080
