services:

  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    build:
      context: ./eureka
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - EUREKA_INSTANCE_HOSTNAME=${EUREKA_HOSTNAME}

  config-server:
    image: config-server:latest
    container_name: config-server
    build:
      context: ./configserver
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - EUREKA_INSTANCE_HOSTNAME=${EUREKA_HOSTNAME}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=${CONFIG_GIT_URI}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=${CONFIG_GIT_USERNAME}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=${CONFIG_GIT_PASSWORD}
    depends_on:
      - eureka-server
  rogue-service:
    image: rogue-service:latest
    container_name: rogue-service
    build:
      context: ./rogue-service
    ports:
      - "3000:3000"  # Expose container port 3000 to host port 3000
    environment:
      - PORT=3000  # Internal port the app listens on
      - SPRING_APPLICATION_NAME=rogue-service
      - EUREKA_INSTANCE_HOSTNAME=${EUREKA_HOSTNAME}
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - CONFIG_SERVER_URL=http://config-server:8888
    depends_on:
      - eureka-server
      - config-server
