name: battle-service CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'battle-service/**'
      - '.github/workflows/battle-service-ci.yml'

jobs:
  build:
    name: Build battle-service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - name: Build with Maven
        working-directory: ./battle-service
        run: mvn clean package
