name: Battle Service CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'battle-service/**'
      - '.github/workflows/battle-service-ci.yml'

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      working-directory: ./battle-service
      ecr-repo: battle-service
    secrets:
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
