name: Build and Push

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      ecr-repo:
        required: true
        type: string
    secrets:
      aws-account-id:
        required: true

jobs:
  verify-maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      AWS_REGION: eu-west-2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
      - name: Verify Maven Build
        working-directory: ${{ inputs.working-directory }}
        run: mvn verify

  build-and-push:
    runs-on: ubuntu-latest
    needs: verify-maven
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: eu-west-2
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.aws-account-id }}:role/github-oidc-ecr-push
          aws-region: ${{ env.AWS_REGION }}
      - uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push Docker image
        working-directory: ${{ inputs.working-directory }}
        run: |
          ECR_URI=${{ secrets.aws-account-id }}.dkr.ecr.${AWS_REGION}.amazonaws.com
          docker build -t ${{ inputs.ecr-repo }}:latest .
          docker tag ${{ inputs.ecr-repo }}:latest $ECR_URI/${{ inputs.ecr-repo }}:latest
          docker push $ECR_URI/${{ inputs.ecr-repo }}:latest
