name: Config Server CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'configserver/**'
      - '.github/workflows/configserver-ci.yml'

jobs:
  build:
    name: Build Config Server
    runs-on: ubuntu-latest

    env:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: ${{ secrets.GIT_CONFIG_URI }}
      SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME: ${{ secrets.GIT_CONFIG_USERNAME }}
      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: ${{ secrets.GIT_CONFIG_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - name: Build with Maven
        working-directory: ./configserver
        run: mvn clean package
