name: Config Server CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'configserver/**'
      - '.github/workflows/configserver-ci.yml'

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      working-directory: ./configserver
      ecr-repo: config-server
    secrets:
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      git-config-uri: ${{ secrets.GIT_CONFIG_URI }}
      git-config-username: ${{ secrets.GIT_CONFIG_USERNAME }}
      git-config-token: ${{ secrets.GIT_CONFIG_TOKEN }}
