name: Eureka CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'eureka/**'
      - '.github/workflows/eureka-ci.yml'

permissions:
  id-token: write
  contents: read
        
jobs:
  build-and-push-eureka:
    uses: ./.github/workflows/build-and-push.yml
    with:
      working-directory: ./eureka
      ecr-repo: eureka-server
    secrets:
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
