name: Eureka CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'eureka/**'
      - '.github/workflows/eureka-ci.yml'
    # 🚨 Avoid running this workflow unnecessarily when unrelated workflows or shared workflows change:
    paths-ignore:
      - '.github/workflows/configserver-ci.yml'
      - '.github/workflows/battle-service-ci.yml'
      - '.github/workflows/build-and-push.yml'


permissions:
  id-token: write
  contents: read
        
jobs:
  build-and-push-eureka:
    uses: ./.github/workflows/build-and-push.yml
    with:
      working-directory: ./eureka
      ecr-repo: eureka-server
    secrets:
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
