name: Eureka CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'eureka/**'
      - '.github/workflows/eureka-ci.yml'

jobs:
  build-maven:
    name: Verify Maven Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      AWS_REGION: eu-west-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - name: Verify Maven Build
        working-directory: ./eureka
        run: mvn verify

  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    needs: build-maven

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: eu-west-2
      ECR_REPO: eureka-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-oidc-ecr-push
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image (multi-stage)
        working-directory: ./eureka
        run: |
          ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com
          docker build -t $ECR_REPO:latest .
          docker tag $ECR_REPO:latest $ECR_URI/$ECR_REPO:latest

      - name: Push Docker image to ECR
        run: |
          ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com
          docker push $ECR_URI/$ECR_REPO:latest
